{
  config,
  lib,
  pkgs,
  homelabLib,
  ...
}:
# ============================================================================
# SERVICE: slskd
#
# Web-based Soulseek client. Optionally bound to the Wireguard namespace like
# Deluge. Completed downloads are auto-imported into the music library with
# beets (see ./beets.nix, which provides the default beets config).
#
# NOTE: `environmentFile` (slskd credentials) defaults to a build-time
# placeholder so the host evaluates - override it with a real secret before use.
# ============================================================================
let
  service = "slskd";
  hl = config.homelab;
  cfg = hl.services.${service};
  ns = hl.services.wireguard-netns.namespace;
in
{
  imports = [ ./beets.nix ];

  options.homelab.services.${service} = {
    enable = lib.mkEnableOption "Enable ${service}";

    importance = homelabLib.mkImportance "low";

    musicDir = lib.mkOption {
      type = lib.types.str;
      default = "${hl.mounts.data}/Music/Library";
    };
    downloadDir = lib.mkOption {
      type = lib.types.str;
      default = "${hl.mounts.data}/Music/Import";
    };
    incompleteDownloadDir = lib.mkOption {
      type = lib.types.str;
      default = "${hl.mounts.data}/Music/Import.tmp";
    };
    url = lib.mkOption {
      type = lib.types.str;
      default = "slskd.${hl.baseDomain}";
    };
    beetsConfigFile = lib.mkOption {
      type = lib.types.path;
      description = "beets config file (defaults to the one generated by ./beets.nix).";
    };
    environmentFile = lib.mkOption {
      type = lib.types.path;
      default = pkgs.writeText "slskd-env" ''
        SLSKD_USERNAME=slskd
        SLSKD_PASSWORD=changeme
        SLSKD_JWT=changemechangemechangemechangeme
      '';
      defaultText = lib.literalMD "a build-time placeholder - override with a secret!";
      description = "File with slskd credentials (SLSKD_USERNAME/PASSWORD/JWT).";
    };

    homepage.name = lib.mkOption {
      type = lib.types.str;
      default = "slskd";
    };
    homepage.description = lib.mkOption {
      type = lib.types.str;
      default = "Web-based Soulseek client";
    };
    homepage.icon = lib.mkOption {
      type = lib.types.str;
      default = "slskd.svg";
    };
    homepage.category = lib.mkOption {
      type = lib.types.str;
      default = "Downloads";
    };
  };

  config = lib.mkIf cfg.enable {
    systemd.tmpfiles.rules = map (x: "d ${x} 0775 ${hl.user} ${hl.group} - -") [
      cfg.musicDir
      "${cfg.musicDir}/.beets"
      cfg.downloadDir
      cfg.incompleteDownloadDir
    ];

    services.${service} = {
      enable = true;
      user = hl.user;
      group = hl.group;
      environmentFile = cfg.environmentFile;
      domain = null;
      settings = {
        integration.scripts.slskd-import-files = {
          on = [
            "DownloadDirectoryComplete"
            "DownloadFileComplete"
          ];
          run =
            let
              slskd-import-files = pkgs.writeScriptBin "slskd-import-files" ''
                #!${lib.getExe pkgs.bash}
                cd ${cfg.musicDir}/.beets
                HOME=${cfg.musicDir}/.beets ${lib.getExe pkgs.beets} -c ${cfg.beetsConfigFile} import -m -A -q ${cfg.downloadDir}
              '';
            in
            {
              executable = "${lib.getExe pkgs.bash}";
              command = "-c ${lib.getExe slskd-import-files}";
            };
        };
        directories = {
          downloads = cfg.downloadDir;
          incomplete = cfg.incompleteDownloadDir;
        };
        shares = {
          directories = [ cfg.musicDir ];
          filters = [
            "\\.ini$"
            "Thumbs.db$"
            "\\.DS_Store$"
          ];
        };
      };
    };

    # Optional Wireguard-namespace binding + socket-activated web proxy.
    systemd.sockets = lib.mkIf hl.services.wireguard-netns.enable {
      "slskd-web-proxy" = {
        enable = true;
        description = "Socket for proxy to the slskd web UI";
        listenStreams = [ (toString config.services.${service}.settings.web.port) ];
        wantedBy = [ "sockets.target" ];
      };
    };
    systemd.services = lib.mkIf hl.services.wireguard-netns.enable {
      slskd = {
        bindsTo = [ "netns@${ns}.service" ];
        environment.DOTNET_USE_POLLING_FILE_WATCHER = "true";
        requires = [
          "network-online.target"
          "${ns}.service"
        ];
        serviceConfig = {
          ReadWritePaths = [ cfg.musicDir ];
          ReadOnlyPaths = lib.mkForce [ ];
          NetworkNamespacePath = [ "/var/run/netns/${ns}" ];
        };
      };
      "slskd-web-proxy" = {
        enable = true;
        description = "Proxy to the slskd web UI in the Wireguard namespace";
        requires = [
          "slskd.service"
          "slskd-web-proxy.socket"
        ];
        after = [
          "slskd.service"
          "slskd-web-proxy.socket"
        ];
        unitConfig.JoinsNamespaceOf = "slskd.service";
        serviceConfig = {
          User = config.services.slskd.user;
          Group = config.services.slskd.group;
          ExecStart = "${pkgs.systemd}/lib/systemd/systemd-socket-proxyd --exit-idle-time=5min 127.0.0.1:${
            toString config.services.${service}.settings.web.port
          }";
          PrivateNetwork = "yes";
        };
      };
    };

    services.caddy.virtualHosts."${cfg.url}".extraConfig = ''
      ${hl.mkCaddyTls}
      reverse_proxy http://127.0.0.1:${toString config.services.${service}.settings.web.port}
    '';
  };
}
